### ISSUE TITLE
Hello, run backend and meet an error.

### ISSUE THREAD

**Issue by louisshiru** [CESNET/Netopeer2GUI#23]
I dont know how to fix this error.
devel depencies were all installed.

**_Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/www/html/ncgui/backend/__main__.py", line 3, in <module>
    from liberouterapi import socketio, app, config
  File "/var/www/html/ncgui/backend/liberouterapi/__init__.py", line 76, in <module>
    import_modules()
  File "/var/www/html/ncgui/backend/liberouterapi/bootstrap.py", line 49, in import_modules
    loaded_mod = __import__(mod_name, fromlist=[str(mod_name)])
  File "/var/www/html/ncgui/backend/liberouterapi/modules/netopeer/__init__.py", line 17, in <module>
    from .schemas import *
  File "/var/www/html/ncgui/backend/liberouterapi/modules/netopeer/schemas.py", line 16, in <module>
    import yang
  File "/usr/lib/python3/dist-packages/yang.py", line 2991, in <module>
    class Decimal64(_object):
  File "/usr/lib/python3/dist-packages/yang.py", line 3000, in Decimal64
    __swig_setmethods__["value"] = _yang.Decimal64_value_set
AttributeError: module '_yang' has no attribute 'Decimal64_value_set'_**

**Comment by jakubman1** [comment]
Hello,
Which OS are you using? Did this error appear as soon as you started the backend or while doing something?
You can also try running the GUI using vagrant to see if you encounter the same error. There is a tutorial on how to run vagrant in README in the vagrant folder.
